/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.CustomersDAO;
import DAO.PetDAO;
import Model.Customers;
import Model.Pet;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import javax.swing.JLabel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84896
 */
public class PetForm extends javax.swing.JFrame {
    String[] columm = new String[]{"Pet_ID", "Pet_Type", "Pet_Breed","Pet_Name", "Color","Age", "Weight", 
                                    "Picture", "Gender","Shots", "Flush","Heath","Price"};
    DefaultTableModel table = new DefaultTableModel();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String imagepath = "C:\\Users\\84896\\Documents\\NetBeansProjects\\DBMS\\src\\icons\\dog.png";
    String current = "";
    /**
     * Creates new form PetForm
     */
    public PetForm() {
        initComponents();
        PetDAO petDATA = new PetDAO();
        ArrayList<Pet> list = petDATA.getAll();
        PetTable.setModel(table);
        table.setColumnIdentifiers(columm);
        addData(list);
        addSearchBoxData();
    }
    public void addData(ArrayList<Pet> list) {
        for(Pet c : list){
            table.addRow(new String[]{c.getPet_ID(), c.getPet_Type(), c.getPet_Breed(), c.getPet_Name(), c.getColor(),String.valueOf(c.getAge()), 
                             String.valueOf(c.getWeight()), c.getPicture(), c.getGender(), c.getShots(), c.getFlush(), c.getHeath(), 
                             String.valueOf(c.getPrice())});
        }
    }
     public void addSearchBoxData(){
         for(String o : columm){
             SearchBox.addItem(o);
         }
     }
    public ImageIcon ResizeImage(String ImagePath, JLabel picture){
        ImageIcon MyImg = new ImageIcon(ImagePath);
        Image img = MyImg.getImage();
        Image newImg = img.getScaledInstance(picture.getWidth(), picture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    public void Refresh(){
        table.setRowCount(0);
        PetDAO petDATA = new PetDAO();
        ArrayList<Pet> list = petDATA.getAll();
        addData(list);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        petidtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pettypetxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        petbreedtxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        petnametxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        colortxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        agetxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        weighttxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ChoosePictureButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ShotsYesButton = new javax.swing.JRadioButton();
        ShotsNoButton = new javax.swing.JRadioButton();
        FlushYesButton = new javax.swing.JRadioButton();
        FlushNoButton = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        healthtxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        pricetxt = new javax.swing.JFormattedTextField();
        DialogPictureLabel = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        ShotsButtonGroup = new javax.swing.ButtonGroup();
        FlushGroupButton = new javax.swing.ButtonGroup();
        GenderGroupButton = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Searchtxt = new javax.swing.JTextField();
        SearchBox = new javax.swing.JComboBox<>();
        PictureLabel = new javax.swing.JLabel();
        Updatepicture = new javax.swing.JButton();

        AddDialog.setMinimumSize(new java.awt.Dimension(725, 650));
        AddDialog.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Add Pet");

        petidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petidtxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Pet_ID");

        pettypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pettypetxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Pet_Type");

        jLabel17.setText("Pet_Breed");

        jLabel18.setText("Pet_Name");

        jLabel19.setText("Color");

        jLabel20.setText("Age");

        jLabel21.setText("Weigth");

        jLabel6.setText("Picture");

        ChoosePictureButton.setText("Choose Picture");
        ChoosePictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosePictureButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Gender");

        jLabel22.setText("Shots");

        ShotsButtonGroup.add(ShotsYesButton);
        ShotsYesButton.setText("Yes");

        ShotsButtonGroup.add(ShotsNoButton);
        ShotsNoButton.setText("No");

        FlushGroupButton.add(FlushYesButton);
        FlushYesButton.setText("Yes");

        FlushGroupButton.add(FlushNoButton);
        FlushNoButton.setText("No");
        FlushNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlushNoButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("Flush");

        jLabel24.setText("Health");

        jLabel25.setText("Price");

        GenderGroupButton.add(MaleRadioButton);
        MaleRadioButton.setText("Male");

        GenderGroupButton.add(FemaleRadioButton);
        FemaleRadioButton.setText("Female");

        pricetxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(petidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(294, 294, 294)
                                        .addComponent(jLabel23)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FlushYesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ChoosePictureButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShotsYesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pettypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(MaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(FemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(ShotsNoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(FlushNoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(209, 209, 209))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(petbreedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(petnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(colortxt)))
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(22, 22, 22)
                                .addComponent(weighttxt)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(healthtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(pricetxt))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(ChoosePictureButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pettypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(petbreedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(ShotsYesButton)
                    .addComponent(ShotsNoButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(petnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlushYesButton)
                    .addComponent(FlushNoButton)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colortxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel24)
                        .addComponent(healthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(weighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        DialogPictureLabel.setMaximumSize(new java.awt.Dimension(400, 300));
        DialogPictureLabel.setMinimumSize(new java.awt.Dimension(200, 150));
        DialogPictureLabel.setPreferredSize(new java.awt.Dimension(200, 150));

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddDialogLayout = new javax.swing.GroupLayout(AddDialog.getContentPane());
        AddDialog.getContentPane().setLayout(AddDialogLayout);
        AddDialogLayout.setHorizontalGroup(
            AddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDialogLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddDialogLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DialogPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
            .addGroup(AddDialogLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(Confirm)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AddDialogLayout.setVerticalGroup(
            AddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDialogLayout.createSequentialGroup()
                .addGroup(AddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDialogLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addComponent(DialogPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Confirm)
                .addGap(17, 17, 17))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PetTable.setMinimumSize(new java.awt.Dimension(100, 120));
        PetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PetTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PetTable);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addGap(18, 18, 18)
                .addComponent(Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("List of Pet");

        jLabel1.setText("Search");

        Searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchtxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Updatepicture.setText("Update Picture");
        Updatepicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatepictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(242, 242, 242))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Updatepicture)
                                        .addGap(27, 27, 27)))))
                        .addComponent(PictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(Updatepicture)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SearchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchtxtKeyReleased
          PetDAO petDATA = new PetDAO();
          ArrayList<Pet> list = petDATA.search((String)SearchBox.getSelectedItem(),Searchtxt.getText());
          table.setRowCount(0);
          addData(list);
          if(Searchtxt.getText().equals("")){
              list = petDATA.getAll();
              table.setRowCount(0);
              addData(list);
            }
    }//GEN-LAST:event_SearchtxtKeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddDialog.setVisible(true);
        
        DialogPictureLabel.setIcon(ResizeImage(imagepath,DialogPictureLabel));
    }//GEN-LAST:event_addButtonActionPerformed

    private void petidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petidtxtActionPerformed

    private void pettypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pettypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pettypetxtActionPerformed

    private void FlushNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlushNoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlushNoButtonActionPerformed

    private void ChoosePictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosePictureButtonActionPerformed
    JFileChooser k = new JFileChooser("C:\\Users\\84896\\Documents\\NetBeansProjects\\DBMS\\src\\icons");
    FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("picture","png", "jpg");
    k.setFileFilter(imageFilter);
    k.setDialogTitle("Open file");
    k.showOpenDialog(null);
    File filename = k.getSelectedFile();
    imagepath = filename.getAbsolutePath();
    if (imagepath != null){
        DialogPictureLabel.setIcon(ResizeImage(String.valueOf(imagepath),DialogPictureLabel));
        System.out.println(imagepath);
    }else{
    JOptionPane.showMessageDialog(rootPane, "Please select your picture!!");
    }
    }//GEN-LAST:event_ChoosePictureButtonActionPerformed
    
    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
    PetDAO petDATA = new PetDAO();
        if(petidtxt.getText().isBlank() || pettypetxt.getText().isBlank() || petbreedtxt.getText().isBlank() ||
           petnametxt.getText().isBlank() || colortxt.getText().isBlank() || agetxt.getText().isBlank() ||
           weighttxt.getText().isBlank() || healthtxt.getText().isBlank() || pricetxt.getText().isBlank() ||
          (!MaleRadioButton.isSelected() && !FemaleRadioButton.isSelected()) ||
           (!ShotsYesButton.isSelected() && !ShotsNoButton.isSelected()) || 
            (!FlushYesButton.isSelected() && !FlushNoButton.isSelected())){
            JOptionPane.showMessageDialog(this, "Missing information");
        }else {
            String PetId = petidtxt.getText();
            String pettype = pettypetxt.getText();
            String petbreed = petbreedtxt.getText();
            String petname = petnametxt.getText();
            String color = colortxt.getText();
            int age = Integer.parseInt(agetxt.getText());
            Float weight = Float.parseFloat(weighttxt.getText());
            String health = healthtxt.getText();
            Float price = Float.parseFloat(pricetxt.getText());
            String picture = imagepath;
            if(picture.equals("C:\\Users\\84896\\Documents\\NetBeansProjects\\DBMS\\src\\icons\\dog.png")){
               JOptionPane.showMessageDialog(this, "Please choose picture");
               return;
            }
            String Gender = "";
            if(MaleRadioButton.isSelected()){
            Gender += "Male";
            }else if(FemaleRadioButton.isSelected()){
            Gender += "Female";
            }
            String Shots = "";
            if(ShotsYesButton.isSelected()){
            Shots += "Yes";
            }else if(ShotsNoButton.isSelected()){
            Shots += "No";
            }
            String Flush ="";
            if(FlushYesButton.isSelected()){
            Flush += "Yes";
            }else if(FlushNoButton.isSelected()){
            Flush += "No";
            }
            
            Pet p = new Pet(PetId,pettype,petbreed,petname,color, age,weight,
                            picture,Gender, Shots, Flush, health,price);
            int result = petDATA.insert(p);
            if(result == 0){
                JOptionPane.showMessageDialog(this, "Add Failed!!");
            }else 
            {
                JOptionPane.showMessageDialog(this, "Add Successful!!");
                table.setRowCount(0);
                ArrayList<Pet> list = petDATA.getAll();
                addData(list);
            }

        }
    }//GEN-LAST:event_ConfirmActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        PetDAO petDATA = new PetDAO();
        int row = PetTable.getSelectedRow();
        if(row == -1){
           JOptionPane.showMessageDialog(PetForm.this, "Please choose Pet to delete!");
        }else {
            int cf = JOptionPane.showConfirmDialog(PetForm.this, "Are you sure to delete this Pet?");
            if(cf == JOptionPane.YES_OPTION) {
                String id = String.valueOf(PetTable.getValueAt(row, 0));
                petDATA.delete(id);
                table.setRowCount(0);
                ArrayList<Pet> list = petDATA.getAll();
                addData(list);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdatepictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatepictureActionPerformed
        if(current.equals("")){
          JOptionPane.showMessageDialog(PetForm.this, "Please choose Picture to update!");
        }else{
            try{
            JFileChooser k = new JFileChooser("C:\\Users\\84896\\Documents\\NetBeansProjects\\DBMS\\src\\icons");
            FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("picture","png", "jpg");
            k.setFileFilter(imageFilter);
            k.setDialogTitle("Open file");
            k.showOpenDialog(this);
            File filename = k.getSelectedFile();
            String newImage = filename.getAbsolutePath();
            PetDAO petDATA = new PetDAO();
            ArrayList<Pet> getpet = petDATA.getbyID(current);
            getpet.get(0).setPicture(newImage);
            petDATA.update(getpet.get(0));
            PictureLabel.setIcon(ResizeImage(newImage,PictureLabel));
            Refresh();
            }catch(Exception e){
                System.out.println(e);
            }
        }
            
    }//GEN-LAST:event_UpdatepictureActionPerformed

    private void PetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetTableMouseClicked
        int row = PetTable.getSelectedRow();
        current = String.valueOf(PetTable.getValueAt(row, 0));
        PetDAO petDATA = new PetDAO();
        ArrayList<Pet> list = petDATA.getbyID(current);
        PictureLabel.setIcon(ResizeImage(list.get(0).getPicture(),PictureLabel));
    }//GEN-LAST:event_PetTableMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        PetDAO PetDATA = new PetDAO();
        int result = 0;
        for(int i = 0 ; i < table.getRowCount();i++) {
            if(table.getValueAt(i, 0).equals("") || 
            table.getValueAt(i, 1).equals("") || 
            table.getValueAt(i, 2).equals("") || 
            table.getValueAt(i, 3).equals("") || 
            table.getValueAt(i, 4).equals("") ||
            table.getValueAt(i, 5).equals("") ||
            table.getValueAt(i, 6).equals("") ||
            table.getValueAt(i, 7).equals("") ||
            table.getValueAt(i, 8).equals("") ||
            table.getValueAt(i, 9).equals("") ||
            table.getValueAt(i, 10).equals("") ||
            table.getValueAt(i, 11).equals("") ||
            table.getValueAt(i, 12).equals("")){
            JOptionPane.showMessageDialog(PetForm.this,"Please enter full information");
           return;
         }else{
            Pet pet = new Pet();
            pet.setPet_ID((String)table.getValueAt(i, 0));
            pet.setPet_Type((String)table.getValueAt(i,1));
            pet.setPet_Breed((String)table.getValueAt(i,2));
            pet.setPet_Name((String)table.getValueAt(i,3));
            pet.setColor((String)table.getValueAt(i,4));
            pet.setAge(Integer.parseInt((String)table.getValueAt(i, 5)));
            pet.setWeight(Float.parseFloat((String)table.getValueAt(i, 6)));
            pet.setPicture((String)table.getValueAt(i,7));
            pet.setGender((String)table.getValueAt(i,8));
            pet.setShots((String)table.getValueAt(i,9));
            pet.setFlush((String)table.getValueAt(i,10));
            pet.setHeath((String)table.getValueAt(i,11));
            pet.setPrice(Float.parseFloat((String)table.getValueAt(i, 12)));
            result = PetDATA.update(pet);   
           }
        }
        JOptionPane.showMessageDialog(PetForm.this,"Updated!!!");
        Refresh();
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddDialog;
    private javax.swing.JButton ChoosePictureButton;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel DialogPictureLabel;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.ButtonGroup FlushGroupButton;
    private javax.swing.JRadioButton FlushNoButton;
    private javax.swing.JRadioButton FlushYesButton;
    private javax.swing.ButtonGroup GenderGroupButton;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JTable PetTable;
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JComboBox<String> SearchBox;
    private javax.swing.JTextField Searchtxt;
    private javax.swing.ButtonGroup ShotsButtonGroup;
    private javax.swing.JRadioButton ShotsNoButton;
    private javax.swing.JRadioButton ShotsYesButton;
    private javax.swing.JButton Update;
    private javax.swing.JButton Updatepicture;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField colortxt;
    private javax.swing.JTextField healthtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField petbreedtxt;
    private javax.swing.JTextField petidtxt;
    private javax.swing.JTextField petnametxt;
    private javax.swing.JTextField pettypetxt;
    private javax.swing.JFormattedTextField pricetxt;
    private javax.swing.JTextField weighttxt;
    // End of variables declaration//GEN-END:variables
}
